# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.

import pandas as pd
import yaml

# Import configuration files
params = yaml.load(open("config/params.yml", "r"), Loader=yaml.SafeLoader)
features = yaml.load(open("config/features.yml", "r"), Loader=yaml.SafeLoader)

# Generate useful variables
SECONDARY_ANIS = params["drep"]["secondary_anis"]


# Import subworkflows
include: "rules/folders.smk"
include: "rules/__functions__.smk"
include: "rules/mags.smk"
include: "rules/checkm2.smk"
include: "rules/drep.smk"
include: "rules/gtdbtk.smk"
include: "rules/dram.smk"
include: "rules/checkm.smk"


rule all:
    """Run the entire pipeline"""
    input:
        rules.checkm.input,
        rules.checkm2.output,
        rules.drep.input,
        rules.gtdbtk.input,
        rules.dram.input,
