# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.

import pandas as pd
import yaml


# Import configuration files
configfile: "config/config.yml"


features = yaml.load(open(config["features"], "r"), Loader=yaml.SafeLoader)
params = yaml.load(open(config["params"], "r"), Loader=yaml.SafeLoader)

# Generate useful variables
SECONDARY_ANIS = params["drep"]["secondary_anis"]

RESULTS = Path("results")


# Import subworkflows
include: "rules/functions.smk"
include: "rules/folders.smk"
include: "rules/mags.smk"
include: "rules/checkm2.smk"
include: "rules/drep.smk"
include: "rules/gtdbtk.smk"
include: "rules/dram.smk"
include: "rules/quast.smk"


rule all:
    """Run the entire pipeline"""
    input:
        rules.checkm2__all.input,
        rules.drep__all.input,
        rules.gtdbtk__all.input,
        rules.dram__all.input,
        rules.quast__all.input,
