# Default resources for snakemake
---
__use_yte__: true


default-resources:
    runtime: 1h
    mem_mb: 1G


set-threads:
    drep__: 24
    checkm2: 24
    dram__annotate__: 24
    gtdbtk__classify_wf__: 24
    quast__: 4


set-resources:
    drep__:
        mem_mb: 64G
        runtime: 7d
    checkm2:
        mem_mb: 16G
    dram__annotate__:
        mem_mb: 64G
        runtime: 1d
    dram__distill__:
        mem_mb: 16G
        runtime: 1d
    gtdbtk__classify_wf__:
        mem_mb: 64 * 1024 * 2 ** (attempt - 1)
        runtime: 1d
    quast:
        mem_mb: 8G
