# Default resources for snakemake
---
__use_yte__: true


default-resources:
    runtime: 1h
    mem_mb: 1G


set-threads:
    checkm2__predict__: 24
    dram__annotate_archive__: 24
    drep__dereplicate__: 24
    drep__get_fasta__: 24
    drep__tarball__: 24
    gtdbtk__classify_wf__: 24


set-resources:
    checkm2__predict__:
        mem_mb: 16G
        runtime: 6h
    dram__annotate__:
        mem_mb: 8G
        runtime: 1d
    dram__distill__:
        mem_mb: 16G
        runtime: 1d
    drep__dereplicate__:
        mem_mb: 64G
        runtime: 6h
    drep__tarball__:
        runtime: 6h
    gtdbtk__classify_wf__:
        mem_mb: 128G
        runtime: 6h
