# Default resources for snakemake
---
__use_yte__: true


default-resources:
    runtime: 1h
    mem_mb: 1G


set-threads:
    checkm__lineage_wf__: 24
    checkm__qa__: 4
    checkm__archive__: 24
    checkm2__predict__: 24
    dram__annotate_archive__: 24
    drep__dereplicate__: 24
    drep__get_fasta__: 24
    drep__tarball__: 24
    gtdbtk__classify_wf__: 24


set-resources:
    checkm__lineage_wf__:
        mem_mb: 128G
        runtime: 2d
    checkm__qa__:
        mem_mb: 8G
        runtime: 12h
    checkm__archive__:
        mem_mb: 2G
        runtime: 2h
    checkm2__predict__:
        mem_mb: 16G
        runtime: 6h
    dram__annotate__:
        mem_mb: 8G
        runtime: 1d
    dram__annotate__aggregate_annotations__:
        mem_mb: 4G
    dram__annotate__aggregate_rrnas__:
        mem_mb: 4G
    dram__annotate__aggregate_trnas__:
        mem_mb: 4G
    dram__distill__:
        mem_mb: 16G
        runtime: 1d
    dram__gtf__:
        mem_mb: 8G
    drep__dereplicate__:
        mem_mb: 64G
        runtime: 6h
    drep__tarball__:
        runtime: 6h
    gtdbtk__classify_wf__:
        mem_mb: 128G
        runtime: 1d
