# Paths and parameters relative to references
---
mag_catalogue_dir: resources/mag_catalogue/

databases:
  checkm2: resources/databases/checkm2/20210323/uniref100.KO.1.dmnd
  checkv: resources/databases/checkv/20230320/checkv-db-v1.5/
  dram: resources/databases/dram/20230811
  genomad: resources/databases/genomad/genomad_db_v1.7
  gtdbtk: resources/databases/gtdbtk/release214
  kraken2:  # add entries as necessary
    refseq500: resources/databases/kraken2/kraken2_RefSeqV205_Complete_500GB/20220505/
  singlem: resources/databases/singlem/S3.2.1.GTDB_r214.metapackage_20231006.smpkg.zb
  virsorter2: resources/databases/virsorter2/20200511/
