# Execution parameters
---
checkm2:
  extra: ""

dram:
  annotate:
    min_contig_size: 1500
  distill:

gtdbtk:
  extra: ""

drep:
  secondary_anis: 
    - 0.90
    - 0.95
    - 0.98
    - 0.99
  minimum_completeness: 75
  maximum_contamination: 25
